# ══════════════════════════════════════════════════════
#  SonarCloud — Configuración del proyecto
#  Sistema de Control de Calidad de Neumáticos
# ══════════════════════════════════════════════════════

sonar.projectKey=unaipini_Entrega-2.1_FabricaNeumaticos
sonar.organization=deusto
sonar.projectName=Sistema de Control de Calidad de Neumaticos
sonar.projectVersion=1.0

# Fuentes
sonar.sources=subsistema_a_planta,subsistema_b_calidad
sonar.tests=subsistema_a_planta/tests,subsistema_b_calidad/tests,tests_sistema

# Cobertura
sonar.python.coverage.reportPaths=coverage_a.xml,coverage_b.xml

# Exclusiones
sonar.exclusions=**/__init__.py, **/data/**, **/tests/**, tests_sistema/**

# Codificación
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
